import React, { useState, useEffect } from 'react';
import { useApp } from '../context/AppContext';
import { Topic, Role, Infographic } from '../types';
import { generateInfographicImage } from '../services/geminiService';

const Infographics = () => {
  const { infographics, topics, currentUser, addInfographic, deleteInfographic } = useApp();
  
  // State quản lý Khối lớp và Chủ đề
  const [selectedGrade, setSelectedGrade] = useState<10 | 11 | 12>(10);
  const [selectedTopicId, setSelectedTopicId] = useState<string>('ALL');
  const [viewingImage, setViewingImage] = useState<string | null>(null);

  // Form State
  const [activeForm, setActiveForm] = useState<'NONE' | 'UPLOAD' | 'AI'>('NONE');
  const [newTitle, setNewTitle] = useState('');
  const [newDesc, setNewDesc] = useState('');
  const [newTopicId, setNewTopicId] = useState<string>('');
  const [newImage, setNewImage] = useState<string>('');
  const [newImageName, setNewImageName] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const canEdit = currentUser?.role === Role.ADMIN || currentUser?.role === Role.TEACHER;

  // --- LỌC DỮ LIỆU ---
  // 1. Lọc Topics theo Khối đang chọn
  const gradeTopics = topics.filter(t => t.grade === selectedGrade);

  // 2. Lọc Infographics theo Khối
  const gradeInfographics = infographics.filter(i => {
      const topic = topics.find(t => t.id === i.topicId);
      return topic?.grade === selectedGrade;
  });

  // 3. Lọc chi tiết theo Topic ID nếu user chọn cụ thể
  const displayedInfographics = selectedTopicId === 'ALL'
    ? gradeInfographics
    : gradeInfographics.filter(i => i.topicId === selectedTopicId);

  // Reset Topic khi đổi Grade
  useEffect(() => {
      setSelectedTopicId('ALL');
  }, [selectedGrade]);

  // UI Helper: Theme theo khối
  const getGradeTheme = (grade: number) => {
      switch(grade) {
          case 10: return { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200', icon: 'text-blue-500', bar: 'bg-blue-500', shadow: 'shadow-blue-100', gradient: 'from-blue-500 to-cyan-400' };
          case 11: return { bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200', icon: 'text-purple-500', bar: 'bg-purple-500', shadow: 'shadow-purple-100', gradient: 'from-purple-500 to-fuchsia-400' };
          case 12: return { bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200', icon: 'text-orange-500', bar: 'bg-orange-500', shadow: 'shadow-orange-100', gradient: 'from-orange-500 to-amber-400' };
          default: return { bg: 'bg-gray-50', text: 'text-gray-700', border: 'border-gray-200', icon: 'text-gray-500', bar: 'bg-gray-500', shadow: 'shadow-gray-100', gradient: 'from-gray-500 to-gray-400' };
      }
  };

  const currentTheme = getGradeTheme(selectedGrade);

  // --- HANDLERS ---
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (!file.type.startsWith('image/')) {
        alert('Vui lòng chọn file hình ảnh.');
        return;
      }
      setNewImageName(file.name);
      const reader = new FileReader();
      reader.onload = (event) => {
        setNewImage(event.target?.result as string || '');
      };
      reader.readAsDataURL(file);
    }
  };

  const handleGenerateAI = async () => {
    if (!newTitle) {
      alert('Vui lòng nhập tiêu đề trước để AI có thể tạo ảnh phù hợp.');
      return;
    }
    setIsGenerating(true);
    const topic = topics.find(t => t.id === newTopicId);
    const topicContext = topic ? `Subject: ${topic.name}.` : '';
    const prompt = `Educational infographic about "${newTitle}". ${topicContext} Description: ${newDesc}. Style: Professional, clean, vector flat design, high resolution, educational visualization.`;
    const base64Image = await generateInfographicImage(prompt);
    
    if (base64Image) {
      setNewImage(base64Image);
      setNewImageName('Generated by Gemini AI');
    } else {
      alert('Không thể tạo ảnh lúc này. Vui lòng thử lại.');
    }
    setIsGenerating(false);
  };

  const handleAddInfographic = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle || !newTopicId || !newImage) {
        alert('Vui lòng điền đầy đủ thông tin');
        return;
    }
    const newInfo: Infographic = {
        id: Date.now().toString(),
        title: newTitle,
        description: newDesc,
        topicId: newTopicId,
        imageUrl: newImage,
        createdAt: new Date().toISOString()
    };
    addInfographic(newInfo);
    resetForm();
  };

  const resetForm = () => {
    setNewTitle('');
    setNewDesc('');
    setNewTopicId('');
    setNewImage('');
    setNewImageName('');
    setActiveForm('NONE');
  };

  return (
    <div className="space-y-8 pb-12">
       {/* 1. Header & Controls */}
       <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4">
           <div>
               <h2 className="text-3xl font-black text-gray-800 tracking-tight">Thư viện Infographic</h2>
               <p className="text-gray-500 mt-1 font-medium">Trực quan hóa kiến thức Tin học chương trình Cánh Diều</p>
           </div>
           
           {canEdit && (
               <div className="flex space-x-3">
                   <button 
                       onClick={() => { setActiveForm('UPLOAD'); setNewImage(''); }}
                       className="px-5 py-2.5 rounded-xl font-bold shadow-sm flex items-center transition-all bg-white border border-gray-200 text-gray-700 hover:bg-gray-50 hover:border-gray-300"
                   >
                       <i className="fas fa-upload mr-2 text-green-600"></i> Tải ảnh
                   </button>
                   <button 
                       onClick={() => { setActiveForm('AI'); setNewImage(''); }}
                       className="px-5 py-2.5 rounded-xl font-bold shadow-lg shadow-purple-100 flex items-center transition-all bg-gradient-to-r from-purple-600 to-indigo-600 text-white hover:scale-105"
                   >
                       <i className="fas fa-magic mr-2"></i> Tạo AI
                   </button>
               </div>
           )}
       </div>

       {/* 2. Grade Selection Cards (3 Items) */}
       <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
           {[10, 11, 12].map((grade) => {
               const theme = getGradeTheme(grade);
               const isActive = selectedGrade === grade;
               
               // Calculate count for progress bar visualization
               const count = infographics.filter(i => {
                   const t = topics.find(topic => topic.id === i.topicId);
                   return t?.grade === grade;
               }).length;
               // Fake max for progress bar visual (e.g., target 20 infographics per grade)
               const maxTarget = 20; 
               const progress = Math.min(100, (count / maxTarget) * 100);

               return (
                   <button
                       key={grade}
                       onClick={() => setSelectedGrade(grade as any)}
                       className={`relative p-6 rounded-2xl text-left transition-all duration-300 border-2 overflow-hidden group ${
                           isActive 
                           ? `bg-white ${theme.border} ring-4 ring-offset-2 ring-opacity-50 ring-${theme.text.split('-')[1]}-300 shadow-xl scale-[1.02]` 
                           : 'bg-white border-transparent hover:border-gray-200 hover:shadow-lg opacity-80 hover:opacity-100'
                       }`}
                   >
                       {/* Background Decoration */}
                       <div className={`absolute top-0 right-0 w-32 h-32 bg-gradient-to-bl ${theme.gradient} opacity-10 rounded-bl-full -mr-10 -mt-10 transition-opacity group-hover:opacity-20`}></div>

                       <div className="flex justify-between items-start mb-4 relative z-10">
                           <div className={`w-14 h-14 rounded-2xl flex items-center justify-center text-2xl shadow-sm ${theme.bg} ${theme.icon}`}>
                               <i className="fas fa-layer-group"></i>
                           </div>
                           {isActive && <i className={`fas fa-check-circle text-2xl ${theme.icon}`}></i>}
                       </div>
                       
                       <div className="relative z-10">
                            <h3 className={`text-3xl font-black ${isActive ? 'text-gray-800' : 'text-gray-500'}`}>
                                KHỐI {grade}
                            </h3>
                            <p className="text-xs text-gray-400 font-bold uppercase tracking-wider mb-6">Sách Cánh Diều</p>
                            
                            {/* Progress Bar Section */}
                            <div className="mt-4">
                                <div className="flex justify-between text-[10px] font-bold uppercase mb-1">
                                    <span className={theme.text}>Kho tài liệu</span>
                                    <span className="text-gray-400">{count} files</span>
                                </div>
                                <div className="w-full h-2 bg-gray-100 rounded-full overflow-hidden">
                                    <div 
                                        className={`h-full ${theme.bar} transition-all duration-1000`} 
                                        style={{ width: `${progress}%` }}
                                    ></div>
                                </div>
                            </div>
                       </div>
                   </button>
               );
           })}
       </div>

       {/* 3. Topic Filters (Pills) */}
       <div className="bg-white p-2 rounded-2xl border border-gray-200 shadow-sm flex overflow-x-auto space-x-2 scrollbar-hide">
           <button
                onClick={() => setSelectedTopicId('ALL')}
                className={`px-6 py-3 rounded-xl text-sm font-bold whitespace-nowrap transition-all ${
                    selectedTopicId === 'ALL' 
                    ? `bg-gray-800 text-white shadow-md` 
                    : 'text-gray-500 hover:bg-gray-100'
                }`}
            >
                Tất cả chủ đề
            </button>
            {gradeTopics.map(t => (
                <button
                    key={t.id}
                    onClick={() => setSelectedTopicId(t.id)}
                    className={`px-5 py-3 rounded-xl text-sm font-bold whitespace-nowrap transition-all flex items-center ${
                        selectedTopicId === t.id 
                        ? `${currentTheme.bg} ${currentTheme.text} border ${currentTheme.border} shadow-sm` 
                        : 'text-gray-500 hover:bg-gray-50 border border-transparent'
                    }`}
                >
                    <i className={`fas ${t.icon} mr-2 opacity-70`}></i>
                    Tháng {t.month}: {t.name.split(':')[0]}
                </button>
            ))}
       </div>

       {/* 4. Upload/Create Form */}
       {activeForm !== 'NONE' && canEdit && (
           <div className={`bg-white p-8 rounded-3xl shadow-xl border-2 animate-fade-in-down ${activeForm === 'AI' ? 'border-purple-200 ring-4 ring-purple-50' : 'border-green-200 ring-4 ring-green-50'}`}>
               <div className="flex justify-between items-center mb-6 border-b border-gray-100 pb-4">
                    <h3 className={`font-black text-xl flex items-center ${activeForm === 'AI' ? 'text-purple-700' : 'text-green-700'}`}>
                        {activeForm === 'AI' ? <><i className="fas fa-magic mr-3"></i> Tạo Infographic bằng AI</> : <><i className="fas fa-cloud-upload-alt mr-3"></i> Tải Infographic lên</>}
                    </h3>
                    <button onClick={resetForm} className="w-8 h-8 flex items-center justify-center rounded-full bg-gray-100 text-gray-500 hover:bg-red-100 hover:text-red-500 transition-colors">
                        <i className="fas fa-times"></i>
                    </button>
               </div>
               <form onSubmit={handleAddInfographic} className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="md:col-span-2">
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-2">Tiêu đề ảnh</label>
                        <input 
                            type="text" 
                            className="w-full p-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-brand-500 focus:outline-none font-medium"
                            value={newTitle}
                            onChange={(e) => setNewTitle(e.target.value)}
                            placeholder={activeForm === 'AI' ? "Ví dụ: Sơ đồ khối cấu trúc rẽ nhánh" : "Tiêu đề của ảnh"}
                        />
                    </div>
                    
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-2">Chủ đề (Thuộc Khối {selectedGrade})</label>
                        <select 
                            className="w-full p-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-brand-500 focus:outline-none bg-white"
                            value={newTopicId}
                            onChange={(e) => setNewTopicId(e.target.value)}
                        >
                            <option value="">-- Chọn chủ đề --</option>
                            {gradeTopics.map(t => (
                                <option key={t.id} value={t.id}>Tháng {t.month}: {t.name}</option>
                            ))}
                        </select>
                    </div>

                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-2">
                            {activeForm === 'AI' ? 'Hình ảnh (Được tạo tự động)' : 'File hình ảnh'}
                        </label>
                        
                        {activeForm === 'UPLOAD' ? (
                             <label className="cursor-pointer bg-gray-50 border-2 border-dashed border-gray-300 rounded-xl hover:bg-white hover:border-brand-400 transition-all h-[50px] flex items-center justify-center text-gray-600 font-bold text-sm">
                                 <i className="fas fa-image mr-2 text-brand-500"></i> Chọn từ máy tính
                                 <input type="file" accept="image/*" className="hidden" onChange={handleFileUpload} />
                             </label>
                        ) : (
                             <button
                                type="button"
                                onClick={handleGenerateAI}
                                disabled={isGenerating || !newTitle}
                                className={`w-full px-4 py-3 rounded-xl border font-bold flex items-center justify-center transition-all ${
                                    isGenerating 
                                    ? 'bg-gray-100 text-gray-400 border-gray-200 cursor-not-allowed' 
                                    : 'bg-purple-50 text-purple-700 border-purple-200 hover:bg-purple-100 hover:shadow-md'
                                }`}
                             >
                                {isGenerating ? <><i className="fas fa-spinner fa-spin mr-2"></i> Đang vẽ...</> : <><i className="fas fa-paint-brush mr-2"></i> Tạo ngay</>}
                             </button>
                        )}
                        
                        {newImageName && <p className="text-xs text-green-600 mt-2 font-bold flex items-center"><i className="fas fa-check-circle mr-1"></i> {newImageName}</p>}
                    </div>

                    <div className="md:col-span-2">
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-2">Mô tả {activeForm === 'AI' ? '(Gợi ý cho AI)' : 'ngắn'}</label>
                        <textarea 
                            className="w-full p-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-brand-500 focus:outline-none"
                            rows={2}
                            value={newDesc}
                            onChange={(e) => setNewDesc(e.target.value)}
                            placeholder={activeForm === 'AI' ? "Mô tả chi tiết để AI vẽ chính xác hơn..." : "Mô tả nội dung chính..."}
                        />
                    </div>
                    
                    {newImage && (
                        <div className="md:col-span-2 mt-2">
                             <p className="text-xs font-bold text-gray-500 uppercase mb-2">Xem trước:</p>
                             <div className="relative group rounded-xl overflow-hidden border border-gray-200 bg-gray-50">
                                <img src={newImage} alt="Preview" className="h-64 w-full object-contain" />
                                {activeForm === 'AI' && (
                                    <button 
                                        type="button" 
                                        onClick={handleGenerateAI}
                                        className="absolute bottom-3 right-3 bg-white text-purple-700 px-4 py-2 rounded-lg shadow-lg text-xs font-bold hover:bg-purple-50 opacity-0 group-hover:opacity-100 transition-opacity"
                                    >
                                        <i className="fas fa-redo mr-2"></i> Vẽ lại
                                    </button>
                                )}
                             </div>
                        </div>
                    )}

                    <div className="md:col-span-2 text-right border-t border-gray-100 pt-4 mt-2">
                        <button type="button" onClick={resetForm} className="text-gray-500 font-bold px-6 py-3 mr-2 hover:bg-gray-100 rounded-xl transition-colors">Hủy bỏ</button>
                        <button type="submit" disabled={!newImage} className={`px-8 py-3 rounded-xl font-bold shadow-lg transition-transform transform active:scale-95 text-white ${!newImage ? 'bg-gray-300 cursor-not-allowed' : (activeForm === 'AI' ? 'bg-purple-600 hover:bg-purple-700' : 'bg-green-600 hover:bg-green-700')}`}>
                            <i className="fas fa-save mr-2"></i> Lưu vào thư viện
                        </button>
                    </div>
               </form>
           </div>
       )}

       {/* 5. Grid Gallery */}
       {displayedInfographics.length === 0 ? (
           <div className="text-center py-24 bg-white rounded-3xl border-2 border-dashed border-gray-200">
               <div className={`w-24 h-24 rounded-full ${currentTheme.bg} flex items-center justify-center mx-auto mb-4`}>
                   <i className={`fas fa-images text-4xl ${currentTheme.text} opacity-50`}></i>
               </div>
               <p className="text-gray-500 font-medium">Chưa có Infographic nào cho bộ lọc này.</p>
           </div>
       ) : (
           <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 animate-fade-in">
               {displayedInfographics.map(item => {
                   const topic = topics.find(t => t.id === item.topicId);
                   return (
                       <div key={item.id} className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-xl transition-all group flex flex-col h-full">
                           {/* Image Container */}
                           <div className="relative h-56 overflow-hidden bg-gray-100 cursor-pointer" onClick={() => setViewingImage(item.imageUrl)}>
                               <img 
                                   src={item.imageUrl} 
                                   alt={item.title} 
                                   className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                               />
                               {/* Gradient Overlay on Hover */}
                               <div className="absolute inset-0 bg-gradient-to-t from-purple-900/90 to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-end justify-between p-4">
                                    <div className="text-white">
                                        <p className="text-[10px] font-bold uppercase tracking-wider mb-1 opacity-90">Click để xem</p>
                                    </div>
                               </div>
                               
                               {/* Delete Button */}
                               {canEdit && (
                                   <button 
                                       onClick={(e) => { e.stopPropagation(); deleteInfographic(item.id); }}
                                       className="absolute top-2 right-2 bg-white/90 text-red-500 w-8 h-8 rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity hover:bg-red-500 hover:text-white shadow-sm backdrop-blur-sm"
                                       title="Xóa ảnh"
                                   >
                                       <i className="fas fa-trash-alt text-xs"></i>
                                   </button>
                               )}
                           </div>
                           
                           <div className="p-5 flex-1 flex flex-col">
                               {topic && (
                                   <div className={`text-[10px] font-black uppercase tracking-widest mb-2 ${currentTheme.text}`}>
                                       Tháng {topic.month}
                                   </div>
                               )}
                               <h3 className="font-bold text-gray-800 text-base mb-2 line-clamp-2 leading-snug" title={item.title}>{item.title}</h3>
                               <p className="text-xs text-gray-500 line-clamp-2 mb-4 h-8 leading-relaxed">{item.description}</p>
                               
                               <div className="mt-auto pt-3 border-t border-gray-50 flex justify-between items-center">
                                   <a 
                                      href={item.imageUrl} 
                                      download="infographic.png"
                                      className="flex items-center text-xs font-bold text-gray-500 hover:text-brand-600 bg-gray-50 hover:bg-brand-50 px-3 py-1.5 rounded-lg transition-colors"
                                      onClick={(e) => e.stopPropagation()}
                                   >
                                       <i className="fas fa-download mr-1.5"></i> Tải ảnh
                                   </a>
                                   <span className="text-[10px] text-gray-400 font-bold bg-gray-50 px-2 py-1 rounded">IMG</span>
                               </div>
                           </div>
                       </div>
                   );
               })}
           </div>
       )}

       {/* Lightbox Modal */}
       {viewingImage && (
           <div className="fixed inset-0 z-50 flex items-center justify-center bg-purple-900/95 backdrop-blur-sm p-4 animate-fade-in" onClick={() => setViewingImage(null)}>
               <button 
                   className="absolute top-6 right-6 text-white/50 text-4xl hover:text-white transition-colors focus:outline-none z-50"
                   onClick={() => setViewingImage(null)}
               >
                   <i className="fas fa-times"></i>
               </button>
               
               <img 
                   src={viewingImage} 
                   alt="Full size infographic" 
                   className="max-w-full max-h-[85vh] rounded-lg shadow-2xl transform transition-transform"
                   onClick={(e) => e.stopPropagation()} 
               />
               
               <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 z-50">
                    <a 
                        href={viewingImage} 
                        download="infographic-edulms.png"
                        onClick={(e) => e.stopPropagation()}
                        className="bg-white text-purple-900 px-8 py-3 rounded-full font-black text-sm shadow-2xl hover:bg-purple-50 transition-colors flex items-center group"
                    >
                        <i className="fas fa-download mr-2 text-purple-700 group-hover:animate-bounce"></i> Tải về máy
                    </a>
               </div>
           </div>
       )}
    </div>
  );
};

export default Infographics;